  name: Deploy to Github Pages
  on:
    push:
      branches:
        - main
  jobs:
    gh-pages-deploy:
      name: Deploying to Github Pages
      runs-on: ubuntu-latest
      steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-node@v2
            with:
              node-version: '12'
          - name: Install packages
            run: yarn install
          - name: Set Creds
            run: git config user.name "V.Paparidis" && git config user.email "v.paparidis@gmail.com"
          - name: Deploy
            run: yarn deploy
